# Generated by Django 5.1.4 on 2024-12-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('TELEPHONES', 'Phones'), ('Electronics', 'Electronics'), ('Latops', 'Laptops'), ('Arts', 'Arts'), ('Food', 'Food'), ('Home', 'Home'), ('Kitchen', 'Kitchen')], max_length=30),
        ),
    ]
