# Generated by Django 5.1.4 on 2024-12-31 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_review_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-createdAt',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'ordering': ('-createdAt',), 'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-createdAt',), 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
    ]
